version: '3.1'

services:
  srv:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: 'routes-db'
    ports:
      - '5432:5432'
    volumes:
      - ./db:/usr/db
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql