version: '3.1'

services:
  srv:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    links:
      - db
    environment:
      DATABASE_URL: 'postgres://${PGUSER}:${PGPASSWORD}@db:5432/${PGDATABASE}'
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - 5432:5432
    volumes:
      - ./db:/usr/db
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql